// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobJRau9a8YdLSnzXYoOeGAEeDev27KYE',
    appId: '1:39473406312:web:12a3ffe6bd34ef2e9c76dd',
    messagingSenderId: '39473406312',
    projectId: 'barrenlanddevleopment',
    authDomain: 'barrenlanddevleopment.firebaseapp.com',
    storageBucket: 'barrenlanddevleopment.firebasestorage.app',
    measurementId: 'G-1DDX5SV4GP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzWohE6Uce21GSJZv0yH0vQYN_pGFP2jE',
    appId: '1:39473406312:ios:bdfe37eb630900fb9c76dd',
    messagingSenderId: '39473406312',
    projectId: 'barrenlanddevleopment',
    storageBucket: 'barrenlanddevleopment.firebasestorage.app',
    iosBundleId: 'com.example.landdevelop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCobJRau9a8YdLSnzXYoOeGAEeDev27KYE',
    appId: '1:39473406312:web:6a2a4fcc606b8db59c76dd',
    messagingSenderId: '39473406312',
    projectId: 'barrenlanddevleopment',
    authDomain: 'barrenlanddevleopment.firebaseapp.com',
    storageBucket: 'barrenlanddevleopment.firebasestorage.app',
    measurementId: 'G-WLMZ5Q5REE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWohE6Uce21GSJZv0yH0vQYN_pGFP2jE',
    appId: '1:39473406312:ios:bdfe37eb630900fb9c76dd',
    messagingSenderId: '39473406312',
    projectId: 'barrenlanddevleopment',
    storageBucket: 'barrenlanddevleopment.firebasestorage.app',
    iosBundleId: 'com.example.landdevelop',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmSiEFBTwbFdd5TLzdLPqXNzZh18Sh1Ag',
    appId: '1:39473406312:android:b7a75e61f9fbea1c9c76dd',
    messagingSenderId: '39473406312',
    projectId: 'barrenlanddevleopment',
    storageBucket: 'barrenlanddevleopment.firebasestorage.app',
  );

}